name: app_version_update
description: An easy and quick way to check if the local app is updated with the same version in their respective stores (Play Store / Apple Store ).

version: 4.0.2
homepage: https://github.com/kauemurakami/app_version_update

environment:
  sdk: ">=2.17.6 <3.7.12"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http:
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
